#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Crypt
version:      0.02
version_from: Crypt.pm
installdirs:  site
requires:
    File::Path:                    0
    Carp:                          0
    File::Basename:                0
    Module::Build:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
