#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Crypt
version:      0.04
version_from: Crypt.pm
installdirs:  site
requires:
    File::Temp:                    0
    ExtUtils::ParseXS:             0
    ExtUtils::Mkbootstrap:         0
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0
    Carp:                          0
    ExtUtils::CBuilder:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
